# Generated by Django 4.1.4 on 2022-12-13 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 14, 26, 24, 144314))),
                ('image', models.ImageField(upload_to='products/images/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('publicated', models.BooleanField(default=False)),
            ],
        ),
    ]
