# Generated by Django 4.1.4 on 2023-09-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_date_create_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 14, 36, 45, 935021)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/images/%Y/%m/%d/'),
        ),
    ]
