# Generated by Django 4.1.4 on 2023-01-31 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 15, 37, 9, 934861)),
        ),
    ]
