# Generated by Django 4.1.4 on 2022-12-19 11:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_date_create'),
        ('user', '0002_client_delete_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 7, 43, 93956))),
                ('amount', models.IntegerField(default=1)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Client', to='user.client')),
                ('purchase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='user.purchase')),
            ],
        ),
    ]
