# Generated by Django 4.1.4 on 2022-12-19 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_purchase_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='purchase',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='hour',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 22, 31, 297290)),
        ),
        migrations.AddField(
            model_name='account',
            name='purchase',
            field=models.ManyToManyField(blank=True, to='user.purchase'),
        ),
    ]
