# Generated by Django 4.1.4 on 2022-12-21 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_account_purchase_purchase_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, upload_to='clients/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='hour',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 14, 32, 28, 443445)),
        ),
    ]
